import type { Config } from 'tailwindcss'

// 1:1 port of the Stitch export token set (DESIGN.md front matter).
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{vue,ts}'],
  theme: {
    extend: {
      colors: {
        primary: '#000000',
        'on-primary': '#ffffff',
        'primary-container': '#1b1b1b',
        'on-primary-container': '#848484',
        'inverse-primary': '#c6c6c6',
        secondary: '#5d5f5f',
        'on-secondary': '#ffffff',
        'secondary-container': '#dfe0e0',
        'on-secondary-container': '#616363',
        tertiary: '#000000',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#410000',
        'on-tertiary-container': '#ff291a',
        'tertiary-fixed': '#ffdad4',
        'tertiary-fixed-dim': '#ffb4a8',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        background: '#f9f9f9',
        'on-background': '#1b1b1b',
        surface: '#f9f9f9',
        'surface-dim': '#dadada',
        'surface-bright': '#f9f9f9',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f3f3',
        'surface-container': '#eeeeee',
        'surface-container-high': '#e8e8e8',
        'surface-container-highest': '#e2e2e2',
        'surface-variant': '#e2e2e2',
        'on-surface': '#1b1b1b',
        'on-surface-variant': '#4c4546',
        'inverse-surface': '#303030',
        'inverse-on-surface': '#f1f1f1',
        outline: '#7e7576',
        'outline-variant': '#cfc4c5',
      },
      borderRadius: { DEFAULT: '0', none: '0' }, // shape language is strictly sharp
      borderWidth: { thin: '2px', thick: '4px' },
      spacing: {
        unit: '4px',
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '64px',
        'border-thin': '2px',
        'border-thick': '4px',
      },
      fontFamily: {
        display: ['Anybody', 'sans-serif'],
        headline: ['Anybody', 'sans-serif'],
        body: ['"Hanken Grotesk"', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'display-lg': ['80px', { lineHeight: '72px', letterSpacing: '-0.04em', fontWeight: '900' }],
        'display-lg-mobile': ['48px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '900' }],
        'headline-lg': ['40px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '800' }],
        'headline-sm': ['24px', { lineHeight: '28px', fontWeight: '800' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '700' }],
      },
      screens: { md: '901px' },
    },
  },
  plugins: [],
} satisfies Config
