import { eventMeta } from '@/data/lineup'
import { assetUrl, canonicalUrl } from './site'

/** Social preview image, generated by scripts/generate-favicons.py. */
export const OG_IMAGE = {
  url: () => assetUrl('/og-image.jpg'),
  width: '1200',
  height: '630',
  alt: 'ROKK — spray-painted wordmark with an anarchy circle-A',
}

/**
 * The MusicEvent node, shared by the home page and every act detail page so
 * the two can't describe the same event differently. Dates come from
 * `eventMeta`, never inlined here.
 */
export function musicEventJsonLd() {
  return {
    '@type': 'MusicEvent',
    name: `${eventMeta.title} — ${eventMeta.claim}`,
    description: `${eventMeta.title}: an outdoor punk concert colliding with a tekk rave. ${eventMeta.date}, doors ${eventMeta.doors}, ${eventMeta.venue}.`,
    startDate: eventMeta.startIso,
    endDate: eventMeta.endIso,
    eventStatus: 'https://schema.org/EventScheduled',
    eventAttendanceMode: 'https://schema.org/OfflineEventAttendanceMode',
    url: canonicalUrl('/'),
    image: [OG_IMAGE.url()],
    location: { '@type': 'Place', name: eventMeta.venue },
    organizer: { '@type': 'Organization', name: 'ROKK', url: canonicalUrl('/') },
  }
}
